import { create } from 'zustand';

/*
 * useStore — Bates + AI-jump project store.
 *
 * All research state is stateless-per-request:
 *   - the user picks a `symbolsUniverse` (S&P 500 list or a custom set)
 *   - each Bates / option-ranking request sends `symbols` and the
 *     backend computes-and-returns
 *   - results are keyed by `sessionId` (auto-generated by the backend)
 *     and cached client-side
 *
 * Persistent slices are only for the raw market feed layer:
 *   quotes, bars, barsBySymbol (from the polygon WS/history stream).
 */

export interface OHLCBar {
  t: number; // unix ms
  o: number;
  h: number;
  l: number;
  c: number;
  v: number;
}

export interface Quote {
  symbol: string;
  price: number;
  bid: number;
  ask: number;
  volume: number;
  ts: number;
}

/* ── Research types ───────────────────────────────────────────── */

export interface PathBundle {
  symbol: string;
  horizon_days: number;
  n_paths: number;
  n_steps: number;
  n_buckets: number;
  spot: number;
  price_min: number;
  price_max: number;
  expected_return: number;
  es_95: number;
  time_days: number[];
  density: number[][];
  p05: number[];
  p50: number[];
  p95: number[];
  /* Spaghetti overlay: up to 200 subsampled paths, each an array of
   * (n_steps + 1) prices. sample_class[i] ∈ {0,1,2} = tail/middle/upside. */
  n_sample_paths: number;
  sample_paths: number[][];
  sample_class: number[];
}

export interface VolSurface {
  symbol: string;
  spot: number;
  n_strikes: number;
  n_maturities: number;
  iv_min: number;
  iv_max: number;
  n_failed: number;
  r: number;
  strikes: number[];
  moneyness: number[];
  maturities_days: number[];
  maturities_years: number[];
  iv: number[][];
}

export interface NewsJumpSignal {
  symbol: string;
  as_of?: number;
  window_hours?: number;
  n_articles: number;
  sentiment_avg: number;
  event_class: string;
  lam_bump: number;
  mu_j_bias: number;
  sigma_j_bump: number;
}

export interface HestonDiagnostics {
  symbol: string;
  n_history_bars: number;
  hist_window_years: number;
  n_paths_used: number;
  params: { v0: number; theta: number; kappa: number; sigma_v: number; rho: number };
  feller: { lhs: number; rhs: number; ok: boolean };
  historical: { mean_ann: number; std_ann: number; skew: number; kurt_excess: number };
  simulated:  { mean_ann: number; std_ann: number; skew: number; kurt_excess: number };
  realized_vol: {
    rv21_mean_vol: number; rv21_std_vol: number;
    sqrt_theta: number; empirical_vol_of_vol: number;
  };
  scores: { moment_match: number; mean_reversion: number; overall: number };
}

export interface BatesBacktestRow {
  symbol: string;
  strike: number;
  dte_days: number;
  right: 'C' | 'P';
  spot: number;
  model_iv: number;
  market_iv: number;
  edge_vol_pts: number;
  premium: number;
  delta: number;
  gamma: number;
  vega: number;
  expected_hedged_pnl: number;
  std_hedged_pnl: number;
  sharpe_daily: number;
  n_paths: number;
  signed_edge: number;
  dollar_edge: number;
}

export interface BatesBacktestSummary {
  n_rows: number;
  n_symbols: number;
  n_strikes: number;
  n_expiries: number;
  n_paths: number;
  horizon_days: number;
  noise_sigma_vol: number;
  r: number;
  mean_edge_vol_pts: number;
  std_edge_vol_pts: number;
  hit_rate_edge_gt_1vol: number;
  avg_hedged_pnl: number;
  avg_sharpe_daily: number;
}

export interface BatesBacktestResult {
  session_id: number;
  summary: BatesBacktestSummary;
  rows: BatesBacktestRow[];
}

export interface OptionRankedRow {
  rank: number;
  symbol: string;
  strike: number;
  dte_days: number;
  right: 'C' | 'P';
  spot: number;
  model_iv: number;
  market_iv: number;
  edge_vol_pts: number;
  dollar_edge: number;
  premium: number;
  delta: number;
  gamma: number;
  vega: number;
  expected_hedged_pnl: number;
  sharpe_daily: number;
  z_bates_edge: number;
  z_news_jump: number;
  z_convexity: number;
  blended_option_score: number;
  signed_edge: number;
}

export interface OptionRankingResult {
  session_id: number;
  n_rows: number;
  weights: { w_edge: number; w_news: number; w_convex: number };
  ranked: OptionRankedRow[];
}

/* ── Paper / Live portfolio types ─────────────────────────────── */

export interface PaperPosition {
  symbol: string;
  qty: number;
  avg_cost: number;
  last_price: number;
  has_price: boolean;
  market_value: number;
  unrealized_pnl: number;
  unrealized_pct: number;
  updated_at: number;
}

export interface PaperOrder {
  id: number;
  symbol: string;
  side: 'buy' | 'sell';
  qty: number;
  fill_price: number;
  cash_delta: number;
  created_at: number;
}

export interface PaperState {
  cash: number;
  initial_cash: number;
  positions_value: number;
  equity: number;
  unrealized_pnl: number;
  total_pnl: number;
  total_return_pct: number;
  positions: PaperPosition[];
  orders: PaperOrder[];
}

export interface LiveHolding {
  symbol: string;
  qty: number;
  avg_cost: number;
  notes: string;
  last_price: number;
  has_price: boolean;
  cost_basis: number;
  market_value: number;
  unrealized_pnl: number;
  unrealized_pct: number;
  updated_at: number;
}

export interface LiveHoldingsState {
  holdings: LiveHolding[];
  total_cost: number;
  total_value: number;
  unrealized_pnl: number;
  unrealized_pct: number;
}

/* ── Store ─────────────────────────────────────────────────────── */

interface State {
  bridgeConnected: boolean;

  /* Real-time feed. */
  quotes: Record<string, Quote>;
  barsBySymbol: Record<string, OHLCBar[]>;

  /* S&P 500 universe (fetched once from backend). */
  sp500Tickers: string[];

  /* Symbol currently focused in TickEvaluation (per-symbol workspace). */
  selectedSymbol: string | null;

  /* Per-symbol research caches. */
  pathBundles:       Record<string, PathBundle>;
  volSurfaces:       Record<string, VolSurface>;
  hestonDiagnostics: Record<string, HestonDiagnostics>;
  newsJumpSignals:   Record<string, NewsJumpSignal>;
  newsJumpAsOf:      number | null;
  newsJumpWindowHours: number;

  /* Multi-symbol research results (Bates + fused ranking). */
  batesBacktest: BatesBacktestResult | null;
  optionRanking: OptionRankingResult | null;

  /* Portfolio slices. */
  paperState:      PaperState      | null;
  liveHoldings:    LiveHoldingsState | null;
  paperError:      string | null;

  /* Busy flags. */
  pathBundleBusy:        boolean;
  volSurfaceBusy:        boolean;
  hestonDiagnosticsBusy: boolean;
  newsJumpBusy:          boolean;
  batesBacktestBusy:     boolean;
  optionRankingBusy:     boolean;
  paperBusy:             boolean;
  liveHoldingsBusy:      boolean;

  _ws: WebSocket | null;

  /* actions */
  send: (cmd: object) => void;
  fetchHistory: (sym: string) => void;
  fetchSp500: () => void;

  selectSymbol: (sym: string | null, horizonDays?: number) => void;

  runPathBundle:        (sym: string, horizonDays: number, nPaths?: number, nBuckets?: number) => void;
  runVolSurface:        (sym: string, opts?: {
    nStrikes?: number; nMaturities?: number;
    moneynessLo?: number; moneynessHi?: number;
    maxMatDays?: number; r?: number;
  }) => void;
  runHestonDiagnostics: (sym: string, nPaths?: number) => void;
  runNewsJumpStatus:    (symbols: string[], windowHours?: number) => void;

  runBatesBacktest: (opts: {
    symbols: string[];
    horizonDays?: number;
    moneynessLo?: number;
    moneynessHi?: number;
    nStrikes?: number;
    expiriesDays?: number[];
    nPaths?: number;
    noiseSigmaVol?: number;
    r?: number;
    seed?: number;
  }) => void;

  runOptionRanking: (opts: {
    symbols: string[];
    horizonDays?: number;
    moneynessLo?: number;
    moneynessHi?: number;
    nStrikes?: number;
    expiriesDays?: number[];
    nPaths?: number;
    noiseSigmaVol?: number;
    r?: number;
    seed?: number;
    wEdge?: number;
    wNews?: number;
    wConvex?: number;
    minUniverse?: number;
  }) => void;

  /* Paper trading. */
  refreshPaper: () => void;
  paperOrder:   (symbol: string, side: 'buy' | 'sell', qty: number) => void;
  paperReset:   () => void;

  /* Live holdings (read-only book). */
  refreshLiveHoldings: () => void;
  liveHoldingsSet: (symbol: string, qty: number, avgCost: number, notes?: string) => void;
}

const WS_URL = 'ws://localhost:3001';

function connect(
  set: (partial: Partial<State> | ((s: State) => Partial<State>)) => void,
  get: () => State,
) {
  const ws = new WebSocket(WS_URL);

  ws.onopen = () => {
    set({ _ws: ws, bridgeConnected: true });
    get().fetchSp500();
  };

  ws.onclose = () => {
    set({ _ws: null, bridgeConnected: false });
    setTimeout(() => connect(set, get), 1500);
  };

  ws.onmessage = (ev) => {
    let msg: Record<string, unknown>;
    try { msg = JSON.parse(ev.data); } catch { return; }
    const type = msg.type as string;

    if (type === 'quote') {
      const q: Quote = {
        symbol: msg.symbol as string,
        price:  msg.price  as number,
        bid:    msg.bid    as number,
        ask:    msg.ask    as number,
        volume: msg.volume as number,
        ts:     msg.ts     as number,
      };
      set((s) => ({ quotes: { ...s.quotes, [q.symbol]: q } }));
      return;
    }

    if (type === 'history') {
      const sym  = msg.symbol as string;
      const bars = (msg.bars as OHLCBar[]) ?? [];
      set((s) => ({ barsBySymbol: { ...s.barsBySymbol, [sym]: bars } }));
      return;
    }

    if (type === 'sp500_list') {
      set({ sp500Tickers: (msg.tickers as string[]) ?? [] });
      return;
    }

    if (type === 'heston_path_bundle') {
      const b = msg as unknown as PathBundle;
      set((s) => ({
        pathBundles:    { ...s.pathBundles, [b.symbol]: b },
        pathBundleBusy: false,
      }));
      return;
    }

    if (type === 'heston_surface') {
      const v: VolSurface = {
        symbol:           msg.symbol           as string,
        spot:             msg.spot             as number,
        n_strikes:        msg.n_strikes        as number,
        n_maturities:     msg.n_maturities     as number,
        iv_min:           msg.iv_min           as number,
        iv_max:           msg.iv_max           as number,
        n_failed:         msg.n_failed         as number,
        r:                msg.r                as number,
        strikes:          (msg.strikes          as number[]) ?? [],
        moneyness:        (msg.moneyness        as number[]) ?? [],
        maturities_days:  (msg.maturities_days  as number[]) ?? [],
        maturities_years: (msg.maturities_years as number[]) ?? [],
        iv:               (msg.iv               as number[][]) ?? [],
      };
      set((s) => ({
        volSurfaces:    { ...s.volSurfaces, [v.symbol]: v },
        volSurfaceBusy: false,
      }));
      return;
    }

    if (type === 'heston_diagnostics') {
      const d = msg as unknown as HestonDiagnostics;
      set((s) => ({
        hestonDiagnostics: { ...s.hestonDiagnostics, [d.symbol]: d },
        hestonDiagnosticsBusy: false,
      }));
      return;
    }

    if (type === 'news_jump') {
      const rows = (msg.rows as NewsJumpSignal[]) ?? [];
      set((s) => {
        const next = { ...s.newsJumpSignals };
        for (const r of rows) next[r.symbol] = r;
        return {
          newsJumpSignals:     next,
          newsJumpAsOf:        (msg.as_of        as number) ?? null,
          newsJumpWindowHours: (msg.window_hours as number) ?? s.newsJumpWindowHours,
          newsJumpBusy:        false,
        };
      });
      return;
    }

    if (type === 'bates_backtest') {
      set({
        batesBacktest: {
          session_id: msg.session_id as number,
          summary:    msg.summary    as BatesBacktestSummary,
          rows:       (msg.rows      as BatesBacktestRow[]) ?? [],
        },
        batesBacktestBusy: false,
      });
      return;
    }

    if (type === 'option_ranking') {
      set({
        optionRanking: {
          session_id: msg.session_id as number,
          n_rows:     msg.n_rows     as number,
          weights:    msg.weights    as OptionRankingResult['weights'],
          ranked:     (msg.ranked    as OptionRankedRow[]) ?? [],
        },
        optionRankingBusy: false,
      });
      return;
    }

    if (type === 'paper_state') {
      const p: PaperState = {
        cash:             msg.cash             as number,
        initial_cash:     msg.initial_cash     as number,
        positions_value:  msg.positions_value  as number,
        equity:           msg.equity           as number,
        unrealized_pnl:   msg.unrealized_pnl   as number,
        total_pnl:        msg.total_pnl        as number,
        total_return_pct: msg.total_return_pct as number,
        positions:        (msg.positions as PaperPosition[]) ?? [],
        orders:           (msg.orders    as PaperOrder[])    ?? [],
      };
      set({ paperState: p, paperBusy: false, paperError: null });
      return;
    }

    if (type === 'live_holdings') {
      const l: LiveHoldingsState = {
        holdings:       (msg.holdings as LiveHolding[]) ?? [],
        total_cost:     msg.total_cost     as number,
        total_value:    msg.total_value    as number,
        unrealized_pnl: msg.unrealized_pnl as number,
        unrealized_pct: msg.unrealized_pct as number,
      };
      set({ liveHoldings: l, liveHoldingsBusy: false });
      return;
    }

    if (type === 'error') {
      const em = (msg.message as string) ?? '';
      if (em.startsWith('paper_')) set({ paperBusy: false, paperError: em });
      console.error('[backend]', em);
      return;
    }
  };
}

export const useStore = create<State>((set, get) => {
  setTimeout(() => connect(set, get), 0);
  return {
    bridgeConnected: false,

    quotes: {},
    barsBySymbol: {},

    sp500Tickers: [],

    selectedSymbol: null,

    pathBundles:       {},
    volSurfaces:       {},
    hestonDiagnostics: {},
    newsJumpSignals:   {},
    newsJumpAsOf:      null,
    newsJumpWindowHours: 48,

    batesBacktest: null,
    optionRanking: null,

    paperState:      null,
    liveHoldings:    null,
    paperError:      null,

    pathBundleBusy:        false,
    volSurfaceBusy:        false,
    hestonDiagnosticsBusy: false,
    newsJumpBusy:          false,
    batesBacktestBusy:     false,
    optionRankingBusy:     false,
    paperBusy:             false,
    liveHoldingsBusy:      false,

    _ws: null,

    send: (cmd) => {
      const ws = get()._ws;
      if (ws && ws.readyState === WebSocket.OPEN)
        ws.send(JSON.stringify(cmd));
    },

    fetchHistory: (sym) => {
      const today = new Date().toISOString().slice(0, 10);
      get().send({
        cmd: 'history', symbol: sym,
        from: '2024-01-01', to: today,
        timespan: 'day', multiplier: 1,
      });
    },

    fetchSp500: () => {
      get().send({ cmd: 'sp500_list' });
    },

    selectSymbol: (sym, horizonDays = 21) => {
      set({ selectedSymbol: sym });
      if (sym) {
        if (!get().barsBySymbol[sym]) get().fetchHistory(sym);
        get().send({ cmd: 'subscribe', symbol: sym });
        get().runPathBundle(sym, horizonDays);
        get().runVolSurface(sym);
        get().runHestonDiagnostics(sym);
      }
    },

    runPathBundle: (sym, horizonDays, nPaths = 5000, nBuckets = 100) => {
      set({ pathBundleBusy: true });
      get().send({
        cmd:          'heston_path_bundle',
        symbol:       sym,
        horizon_days: horizonDays,
        n_paths:      nPaths,
        n_buckets:    nBuckets,
      });
    },

    runVolSurface: (sym, opts = {}) => {
      set({ volSurfaceBusy: true });
      get().send({
        cmd:           'heston_surface',
        symbol:        sym,
        n_strikes:     opts.nStrikes     ?? 21,
        n_maturities:  opts.nMaturities  ?? 12,
        moneyness_lo:  opts.moneynessLo  ?? 0.7,
        moneyness_hi:  opts.moneynessHi  ?? 1.3,
        max_mat_days:  opts.maxMatDays   ?? 180,
        r:             opts.r            ?? 0.04,
      });
    },

    runHestonDiagnostics: (sym, nPaths = 4000) => {
      set({ hestonDiagnosticsBusy: true });
      get().send({ cmd: 'heston_diagnostics', symbol: sym, n_paths: nPaths });
    },

    runNewsJumpStatus: (symbols, windowHours = 48) => {
      if (!symbols || symbols.length === 0) return;
      set({ newsJumpBusy: true });
      get().send({
        cmd:          'news_jump_status',
        symbols,
        window_hours: windowHours,
      });
    },

    runBatesBacktest: (opts) => {
      if (!opts.symbols || opts.symbols.length === 0) return;
      set({ batesBacktestBusy: true });
      get().send({
        cmd:             'bates_backtest_run',
        symbols:         opts.symbols,
        horizon_days:    opts.horizonDays   ?? 30,
        moneyness_lo:    opts.moneynessLo   ?? 0.85,
        moneyness_hi:    opts.moneynessHi   ?? 1.15,
        n_strikes:       opts.nStrikes      ?? 7,
        expiries_days:   opts.expiriesDays  ?? [7, 30, 90],
        n_paths:         opts.nPaths        ?? 256,
        noise_sigma_vol: opts.noiseSigmaVol ?? 0.015,
        r:               opts.r             ?? 0.045,
        seed:            opts.seed          ?? 12345,
      });
    },

    runOptionRanking: (opts) => {
      if (!opts.symbols || opts.symbols.length === 0) return;
      set({ optionRankingBusy: true });
      get().send({
        cmd:             'option_ranking_blend',
        symbols:         opts.symbols,
        horizon_days:    opts.horizonDays   ?? 30,
        moneyness_lo:    opts.moneynessLo   ?? 0.85,
        moneyness_hi:    opts.moneynessHi   ?? 1.15,
        n_strikes:       opts.nStrikes      ?? 7,
        expiries_days:   opts.expiriesDays  ?? [7, 30, 90],
        n_paths:         opts.nPaths        ?? 256,
        noise_sigma_vol: opts.noiseSigmaVol ?? 0.015,
        r:               opts.r             ?? 0.045,
        seed:            opts.seed          ?? 12345,
        w_edge:          opts.wEdge         ?? 0.60,
        w_news:          opts.wNews         ?? 0.27,
        w_convex:        opts.wConvex       ?? 0.13,
        min_universe:    opts.minUniverse   ?? 8,
      });
    },

    refreshPaper: () => {
      set({ paperBusy: true });
      get().send({ cmd: 'paper_state' });
    },

    paperOrder: (symbol, side, qty) => {
      if (!symbol || !(qty > 0)) return;
      set({ paperBusy: true, paperError: null });
      get().send({
        cmd: 'paper_order',
        symbol: symbol.trim().toUpperCase(),
        side, qty,
      });
    },

    paperReset: () => {
      set({ paperBusy: true, paperError: null });
      get().send({ cmd: 'paper_reset' });
    },

    refreshLiveHoldings: () => {
      set({ liveHoldingsBusy: true });
      get().send({ cmd: 'live_holdings' });
    },

    liveHoldingsSet: (symbol, qty, avgCost, notes = '') => {
      if (!symbol) return;
      set({ liveHoldingsBusy: true });
      get().send({
        cmd: 'live_holdings_set',
        symbol: symbol.trim().toUpperCase(),
        qty, avg_cost: avgCost, notes,
      });
    },
  };
});
